import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import { AuthProvider } from "@/providers/auth";
import Footer from "@/components/ui/footer";
import CartProvider from "@/providers/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <AuthProvider>
            <CartProvider>
              <div className="md:container md:mx-auto md:my-8">
                <Header />
              </div>
              <div className="flex-1">{children}</div>
              <div className="md:container md:mx-auto md:my-8">
                <Footer />
              </div>
            </CartProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
